@baseUrl = http://localhost:3000

### Upload sample ext file
POST {{baseUrl}}/api/parse

file=@./src/ext-files/sample-ext.js

# curl -X POST http://localhost:3000/api/parse \
#   -F "file=@./src/ext-files/sample-ext.js"